import assert from "node:assert/strict";
import fs from "node:fs";

const html = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../styles.css", import.meta.url), "utf8");
const js = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");

assert.match(html, /class="total-card pocket-ledger-card[^"]*"/, "monthly total card should opt into the Pocket Ledger treatment");
assert.match(css, /--paper:\s*#f3ecdc/, "Pocket Ledger should use a warmer paper background");
assert.match(css, /\.pocket-ledger-card::before/, "Pocket Ledger total card should have a tactile paper/highlight layer");
assert.match(css, /\.expense-item:active/, "expense rows should have a touch-friendly pressed state");
assert.match(html, /id="styleButton"/, "header should include a style menu button");
assert.match(html, /data-style-option="pocket"/, "style menu should include Option A");
assert.match(html, /data-style-option="neon"/, "style menu should include Option B");
assert.match(html, /data-style-option="swiss"/, "style menu should include Option C");
assert.match(css, /body\[data-style="neon"\]/, "Option B should have a Neon Night theme hook");
assert.match(css, /body\[data-style="swiss"\]/, "Option C should have a Minimal Swiss theme hook");
assert.match(js, /STYLE_KEY/, "selected style should be saved separately from expenses");
assert.match(js, /function applyAppStyle/, "style selection should be applied through a named helper");
assert.match(html, /id="rangeStartInput"/, "overview should include a from-date input");
assert.match(html, /id="rangeEndInput"/, "overview should include a to-date input");
assert.match(html, /data-period-mode="range"/, "overview should include a custom dates mode");
assert.match(css, /\.date-range-controls/, "custom date inputs should be styled for mobile");
assert.match(html, /class="date-range-card"/, "custom date inputs should sit in one connected card");
assert.match(html, /class="range-connector"/, "custom date fields should have a visual from-to connector");
assert.match(css, /\.date-field > span:first-child/, "date labels should be straight above their date inputs");
assert.match(css, /grid-template-columns:\s*minmax\(0,\s*1fr\)\s+24px\s+minmax\(0,\s*1fr\)/, "date range grid should force equal flexible date fields");
assert.match(css, /\.date-field input \{[^}]*min-width:\s*0/s, "native date inputs should not overflow their grid cells");
assert.doesNotMatch(css, /\.range-connector \{[^}]*translateY/s, "range connector should not be vertically nudged off center");
assert.match(html, /class="date-display"/, "range fields should use a custom visible date display");
assert.match(html, /id="rangeStartDisplay"/, "from date should have centered visible text");
assert.match(html, /id="rangeEndDisplay"/, "to date should have centered visible text");
assert.match(css, /\.date-field input \{[^}]*opacity:\s*0/s, "native date inputs should be invisible tap targets");
assert.match(js, /function updateRangeDisplays/, "date display text should be synced from the real inputs");
assert.match(html, /class="total-card pocket-ledger-card money-wheel-card"/, "top total card should be redesigned as a money wheel");
assert.match(html, /id="moneyWheel"/, "top total card should include a category-color wheel layer");
assert.match(css, /\.money-wheel-card/, "money wheel card should have a dedicated circular style hook");
assert.match(css, /\.money-wheel-center/, "money wheel should keep the total amount readable in the center");
assert.match(js, /function categoryWheelGradient/, "category wheel should be generated from category totals");
assert.match(css, /\.money-wheel-card \{[^}]*width:\s*min\(100%,\s*292px\)/s, "money wheel should be slimmer and less oversized");
assert.match(css, /\.money-wheel-card \{[^}]*background:\s*transparent/s, "money wheel card should not paint the transparent center from behind");
assert.match(css, /\.money-wheel-center \{[^}]*position:\s*absolute/s, "money wheel center should be positioned by inset so it cannot shrink around text");
assert.match(css, /\.money-wheel-center \{[^}]*inset:\s*17px/s, "money wheel center should make the category ring narrow");
assert.match(css, /\.money-wheel \{[^}]*mask:\s*radial-gradient/s, "category colors should be clipped to the band between the inner and outer circle lines");
assert.match(css, /\.money-wheel \{[^}]*mask:\s*radial-gradient\(circle closest-side/s, "category band mask should measure from the circle edge, not the square corner");
assert.match(css, /\.money-wheel \{[^}]*#fff calc\(100% - 17px\) 100%/s, "category band mask should use white for the visible ring so Safari renders the colors");
assert.match(css, /\.money-wheel-center \{[^}]*background:\s*transparent/s, "money wheel center should be transparent so category colors remain visible");
assert.match(css, /\.money-wheel-center \{[^}]*border:\s*0/s, "transparent center should not draw a third circle outline");
assert.match(css, /\.money-wheel-center \{[^}]*color:\s*var\(--ink\)/s, "money wheel center should use normal dark text instead of washed-out white text");
assert.match(css, /\.money-wheel-center \{[^}]*display:\s*flex/s, "money wheel center text should be vertically centered as a single stack");
assert.match(css, /\.total-card::after \{[^}]*inset:\s*17px/s, "inner line should align with the transparent center and define the ring edge");
assert.doesNotMatch(css, /body\[data-style="neon"\] \.money-wheel-center \{[^}]*background:/s, "neon style should not repaint the transparent wheel center");
assert.doesNotMatch(css, /body\[data-style="swiss"\] \.money-wheel-center \{[^}]*background:/s, "swiss style should not repaint the transparent wheel center");
assert.doesNotMatch(css, /body\[data-style="swiss"\] \.total-card::after[^}]*display:\s*none/s, "swiss style should keep the same inner circle line as other styles");
assert.match(css, /body\[data-style="neon"\] \.money-wheel-card \{[^}]*background:\s*transparent/s, "neon style should not repaint the money wheel card behind the transparent center");
assert.match(css, /body\[data-style="swiss"\] \.money-wheel-card \{[^}]*background:\s*transparent/s, "swiss style should not repaint the money wheel card behind the transparent center");
assert.match(js, /rangeStartInput"\)\.addEventListener\("input", updateRangeStart\)/, "from-date changes should update immediately on mobile input events");
assert.match(js, /rangeEndInput"\)\.addEventListener\("input", updateRangeEnd\)/, "to-date changes should update immediately on mobile input events");
